### ISSUE TITLE
Recipe card list

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#1]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I need a list of recipe cards
to cook easily a healthy vegan meal

### Description (Text, Scribble, Wireframe, Design)

- It's a long scrolling list of cards
- A card contains a name of the recipe, products, a picture, a hidden instrucion and a bookmark

### Acceptance criteria

- [ ] Cards have to be visually separated
- [ ] The order of the components in the card is: name of the recipe, products, picture, instruction
- [ ] Name of the recipe and instruction are simple text in a good readable size
- [ ] Products are listed vertically
- [ ] Name of the recipe, products and picture are always visible
- [ ] Instruction is hidden and only visible by using toggle function
- [ ] Cards are scrolled vertically

### Tasks

- [ ] Create two cards in App.js
- [ ] Styling
- [ ] Test in mobile to check the size

### Size

medium
