### ISSUE TITLE
Highlighting pictures

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#10]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I need to see the selected products.

### Description

- Pictures are highlighted by adding dark shadow

### Acceptance criteria

- [ ] Pictures have shadwo to toggle
- [ ] Shadow toggles on click

### Tasks

- [ ] Add toggle logic 
- [ ] Finish styling
- [ ] Test toggle function

### Size

medium
