### ISSUE TITLE
Recipe filter

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#11]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I want to filter the recipe cards 
to see only recipes that contains the selected products.

### Description

- No visible impact

### Acceptance criteria

- [ ] Recipe cards can be seen if selected products match with recipe
- [ ] Recipe cards which do not match are not visible

### Tasks

- [ ] Add filter logic 

### Size

large
