### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#24]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I need a navigation
to switch between pages.

### Description

- It's at the bottom of the page
- It's divided into four equal parts
- The description is in the middle of each section

### Acceptance criteria

- [ ] Sections have to be visually separated
- [ ] Text is not too small and can be seen clearly

### Tasks

- [ ] Create component Navigation.js
- [ ] Write names of pages in each section
- [ ] Add routing and paths
- [ ] Styling
- [ ] Test in mobile to check the size

### Size

small
