### ISSUE TITLE
Favorite recipes

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#25]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I want to see my favorite meals
to find them easily.

### Description

- It's a scrolling list of bookmarked cards
- If there are no cards, show a text

### Acceptance criteria

- [ ] Only bookmarked cards can be seen

### Tasks

- [ ] Create component Favorites.js
- [ ] Filter bookmarked cards and show them on this page
- [ ] Add text, if there are no cards
- [ ] Styling
- [ ] Test in mobile to check the size

### Size

small
