### ISSUE TITLE
Shopping list

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#27]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I need a shopping list 
to know which products I need to buy.

### Description

- Under the header is a dropdown menu to choose a product
- Every chosen product is visible
- The product appears as an image
![Shoppinglist](https://user-images.githubusercontent.com/59567629/76415956-778c0580-639a-11ea-9789-b50bea4668f6.jpg)

### Acceptance criteria

- [ ] Dropdown menu contains every product 
- [ ] Every chosen product appears in a list
- [ ] Every chosen product can be deleted

### Tasks

- [ ] Create component Shopping list.js
- [ ] Insert a dropdown menu 
- [ ] Create a grid in which the products appear
- [ ] Create delete button 
- [ ] Styling
- [ ] Test in mobile to check the size

### Size

medium
