### ISSUE TITLE
Start page

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#31]

**Comment by nicolefrydrych** [comment]
### Value statement

As a user 
I want to switch easily
to page with recipes and to shopping list.

### Description

- The page is divided in two equal sections
- Text is written in the middle of each section
- The navigation is at the bottom of the page
![StartPage](https://user-images.githubusercontent.com/59567629/76684467-8aa60c00-660c-11ea-8d55-7b7e7524406f.jpg)

### Acceptance criteria

- [ ] Text is simple in a good readable size
- [ ] Text of same size is in each section
- [ ] Left section leads to page with recipes, right section leads to page with shopping list

### Tasks

- [ ] Create component StartPage.js
- [ ] Divide page in two equal sections
- [ ] Add routing to sections and path to page "Choose a meal" and "Shopping list"
- [ ] Styling
- [ ] Test in mobile to check the size and test routing

### Size

small
