### ISSUE TITLE
Create new card

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#32]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I need to add new cards with recipes
to increase the available selection.

### Description

- A form to add cards with inputs recipe name, instruction and products
- A button to submit [Create card] is at the end of the page
- A button to cancel entered data is below submit button
![CreateRecipe](https://user-images.githubusercontent.com/59567629/76684977-6e0bd300-6610-11ea-8b59-4358b378315b.jpg)

### Acceptance criteria

- [ ] The form reacts on submit (click button)
- [ ] No input field has focus 
- [ ] The form is cleared after submit and cancel
- [ ] The new card is added at the beginning on page "Choose a meal"

### Tasks

- [ ] Create component CreateRecipe.js
- [ ] Create form with three input fields
- [ ] Add styling
- [ ] Test on mobile to ckeck function

### Size

large
