### ISSUE TITLE
Delete card from list

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#46]

**Comment by nicolefrydrych** [comment]
### Value statement

As a user
I want to delete exsisting and created cards
to update my list with recipes.

### Description

- There is a bin icon on each card
![Delete card](https://user-images.githubusercontent.com/59567629/77296357-cf563500-6ce7-11ea-8cd7-aca3c6446d36.jpg)


### Acceptance criteria

- [ ] Add icon and delete function to component Card.js
- [ ] Bin is not visible. After clicking "show more" bin appears
- [ ] Recipe is deleted by using the icon

### Tasks

- [ ] Add icon
- [ ] Add delete logic
- [ ] Test delete function

### Size

small
