### ISSUE TITLE
Showing tips

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#47]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I want to get useful vegan tips
to get inspired by creative ideas.

### Description

- There is a text on the start page
![Vegan tips](https://user-images.githubusercontent.com/59567629/77303430-3decc000-6cf3-11ea-83ae-b0d285556edf.jpg)


### Acceptance criteria

- [ ] Text apperas on the left or right side
- [ ] New tip is shown after reload


### Tasks

- [ ] Create array with mock data in tip.js
- [ ] Implement tips.js in component StartPage.js
- [ ] Add math function to show a random tip from array
- [ ] Add styling
- [ ] Test math function 

### Size

small
