### ISSUE TITLE
Toggle instrucion

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#5]

**Comment by nicolefrydrych** [comment]
### Value statemen

As a vegan person
I can toggle the instruction of a meal.
In order to have an overview of the products and an easily visible picture, the instruction is hidden.


### Description

- There will be a headline "Instruction" 

### Acceptance criteria

- [ ] Instruction is hidden by default
- [ ] Headline doesn't change on tap
- [ ] Each cards expands in place
- [ ] Card expansion is animated 
- [ ] Card expansion is as long as the instruction text

### Tasks

- [ ] Add toggle logic
- [ ] Finish card styling
- [ ] Test toggle function

### Size

medium
