### ISSUE TITLE
Bookmarking

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#6]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I need to bookmark recipe cards
to find quickly the ones I prefer to cook.

### Description 

- A nice bookmark symbol on each card

### Acceptance criteria

- [ ] Bookmark changes color on toggle
- [ ] Bookmark toggles on click

### Tasks

- [ ] Add styling
- [ ] Add toggle logic
- [ ] Test toggle function

### Size

medium
