### ISSUE TITLE
Save bookmark state locally

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#7]

**Comment by nicolefrydrych** [comment]
### Value statement 

As a vegan person
I need to save the state of bookmarked recipe cards
to see my favorite meals after refresh.

### Description 

-  No visible impact

### Acceptance criteria

- [ ] Every change on the state cards should trigger a save to localStorage
- [ ] Reload of the page should load cards from localStorage

### Tasks

- [ ] Create services for localStorage
- [ ] Implement save-logic for cards
- [ ] Test localStorage implementation

### Size

medium
