### ISSUE TITLE
Product list

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#8]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I need a list of products
to select a meal I want to cook.

### Description 

- It's a rectangle
- Twelve product pictures with a square format are inside the rectangle
- Three product pictures are in each row

### Acceptance criteria

- [ ] Rectangle is under the header/above cards
- [ ] Products in the picture can be seen clearly 
- [ ] Pictures are not so small 

### Tasks

- [ ] Create Porduct list component
- [ ] Find twelve pictrues and add to rectangle
- [ ] Styling
- [ ] Test in mobile to check the size

### Size

medium
