### ISSUE TITLE
Toggle product list

### ISSUE THREAD

**Issue by nicolefrydrych** [nicolefrydrych/capstone-project#9]

**Comment by nicolefrydrych** [comment]
### Value statement

As a vegan person
I want to expand the product list to see twelve products.
After selection I want to confirm and reduce list to see 6 products.

### Description

- There are three dots to expand the rectangle
- After expanding the rectangle there is a button at the end of the rectangle on the right side to confirm the selection

### Acceptance criteria

- [ ] There are six pictures by default
- [ ] After expanding rectangle there are 12 pictures
- [ ] Dots don't change on tap
- [ ] Button doesn't change on tap
- [ ] Rectangle expands in place 
- [ ] Rectangle expansion is animated

### Tasks

- [ ] Add click logic to dots to enlarge rectangle
- [ ] Add click logic to button to reduce rectangle
- [ ] Finish styling
- [ ] Test toggle and click function

### Size

medium
